Repository camunda-community-hub/camunda-platform-scenario, pull requests merged in 2021-05, with the labels that each got.

#39 Add businessKey param to statByKey methods.
  core/src/main/java/org/camunda/bpm/scenario/impl/ProcessRunnerImpl.java
  core/src/main/java/org/camunda/bpm/scenario/run/ProcessRunner.java
  test/test-7.0/src/test/java/org/camunda/bpm/scenario/test/processes/StartByTest.java
Labels: improve

#44 Fix test module structure
  test/test-7.6/src/main/resources/.keep
  test/test-7.6/src/test/java/org/camunda/bpm/scenario/test/AbstractTest.java
  test/test-7.6/src/test/java/org/camunda/bpm/scenario/test/boundary/ConditionaBoundaryEventTest.java
  test/test-7.6/src/test/java/org/camunda/bpm/scenario/test/waitstates/ConditionalIntermediateEventTest.java
  test/test-7.6/src/test/java/org/camunda/bpm/scenario/test/waitstates/EventBasedGatewayTest.java
  test/test-7.6/src/test/resources/camunda.cfg.xml
  test/test-7.6/src/test/resources/logback.xml
  test/test-7.6/src/test/resources/org/camunda/bpm/scenario/test/boundary/ConditionalBoundaryEventTest.bpmn
  test/test-7.6/src/test/resources/org/camunda/bpm/scenario/test/waitstates/ConditionalIntermediateEventTest.bpmn
  test/test-7.6/src/test/resources/org/camunda/bpm/scenario/test/waitstates/EventBasedGatewayTest.bpmn
Labels: fix

#46 Add handling bpmn error functionality to user task delegates
  core/src/main/java/org/camunda/bpm/scenario/delegate/TaskDelegate.java
  core/src/main/java/org/camunda/bpm/scenario/impl/waitstate/UserTaskExecutable.java
  test/pom.xml
  test/test-7.12/pom.xml
  test/test-7.12/src/main/resources/.keep
  test/test-7.12/src/test/java/org/camunda/bpm/scenario/test/AbstractTest.java
  test/test-7.12/src/test/java/org/camunda/bpm/scenario/test/errors/UserTaskBoundaryErrorEventTest.java
  test/test-7.12/src/test/resources/camunda.cfg.xml
  test/test-7.12/src/test/resources/logback.xml
  test/test-7.12/src/test/resources/org/camunda/bpm/scenario/test/errors/BoundaryErrorEventTest.bpmn
Labels: improve

#51 Update README.md
  README.md
Labels: chore

#49 Compile core against latest camunda engine version 7.15.0
  .travis.yml
  core/pom.xml
  core/src/main/java/org/camunda/bpm/scenario/impl/delegate/AbstractExternalTaskDelegate.java
  pom.xml
Labels: chore

#48 Extend external task delegate to handle bpmn errors with variables
  core/src/main/java/org/camunda/bpm/scenario/delegate/ExternalTaskDelegate.java
  core/src/main/java/org/camunda/bpm/scenario/impl/waitstate/BusinessRuleTaskExecutable.java
  core/src/main/java/org/camunda/bpm/scenario/impl/waitstate/MessageEndEventExecutable.java
  core/src/main/java/org/camunda/bpm/scenario/impl/waitstate/MessageIntermediateThrowEventExecutable.java
  core/src/main/java/org/camunda/bpm/scenario/impl/waitstate/SendTaskExecutable.java
  core/src/main/java/org/camunda/bpm/scenario/impl/waitstate/ServiceTaskExecutable.java
  test/pom.xml
  test/test-7.10/pom.xml
  test/test-7.10/src/main/resources/.keep
  test/test-7.10/src/test/java/org/camunda/bpm/scenario/test/AbstractTest.java
  test/test-7.10/src/test/java/org/camunda/bpm/scenario/test/errors/BoundaryErrorEventTest.java
  test/test-7.10/src/test/resources/camunda.cfg.xml
  test/test-7.10/src/test/resources/logback.xml
  test/test-7.10/src/test/resources/org/camunda/bpm/scenario/test/errors/BoundaryErrorEventTest.bpmn
Labels: improve

#58 Updated README to reference Camunda Platform
  README.md
Labels: doc

#43 Implement mocking for call activities
  core/src/main/java/org/camunda/bpm/scenario/ProcessScenario.java
  core/src/main/java/org/camunda/bpm/scenario/act/MockedCallActivityAction.java
  core/src/main/java/org/camunda/bpm/scenario/impl/MockedProcessRunnerImpl.java
  core/src/main/java/org/camunda/bpm/scenario/impl/ProcessRunnerImpl.java
  core/src/main/java/org/camunda/bpm/scenario/impl/ScenarioImpl.java
  core/src/main/java/org/camunda/bpm/scenario/impl/WaitstateExecutable.java
  core/src/main/java/org/camunda/bpm/scenario/impl/waitstate/CallActivityExecutable.java
  core/src/main/java/org/camunda/bpm/scenario/run/ProcessRunner.java
  test/test-7.4/src/test/java/org/camunda/bpm/scenario/test/callactivities/CallActivityChildMockingTest.java
  test/test-7.4/src/test/java/org/camunda/bpm/scenario/test/callactivities/CallActivityWithBoundaryInterruptingTimerTest.java
  test/test-7.4/src/test/resources/org/camunda/bpm/scenario/test/callactivities/CallActivityTest.bpmn
  test/test-7.4/src/test/resources/org/camunda/bpm/scenario/test/callactivities/CallActivityWithBoundaryInterruptingTimerTest.bpmn
  test/test-7.4/src/test/resources/org/camunda/bpm/scenario/test/callactivities/Child.bpmn
  test/test-7.5/src/test/java/org/camunda/bpm/scenario/test/errors/CallActivityWithBoundaryErrorEventTest.java
  test/test-7.5/src/test/resources/org/camunda/bpm/scenario/test/errors/CallActivityWithBoundaryErrorEventTest.bpmn
Labels: feature

#60 Fix registering multiple call activities
  core/src/main/java/org/camunda/bpm/scenario/impl/ScenarioImpl.java
  test/test-7.4/src/test/java/org/camunda/bpm/scenario/test/callactivities/MultipleCallActivitiesChildMockingTest.java
  test/test-7.4/src/test/resources/org/camunda/bpm/scenario/test/callactivities/MultipleCallActivitiesTest.bpmn
Labels: fix

#63 Extend user task delegate to handle escalations
  core/src/main/java/org/camunda/bpm/scenario/delegate/TaskDelegate.java
  core/src/main/java/org/camunda/bpm/scenario/impl/waitstate/UserTaskExecutable.java
  test/test-7.12/src/test/java/org/camunda/bpm/scenario/test/errors/UserTaskBoundaryEscalationEventTest.java
  test/test-7.12/src/test/resources/org/camunda/bpm/scenario/test/escalations/UserTaskBoundaryEscalationEventTest.bpmn
Labels: feature

#73 Access variables from delegate
  runner/src/main/java/org/camunda/bpm/scenario/delegate/ProcessInstanceAwareDelegate.java
  runner/src/main/java/org/camunda/bpm/scenario/delegate/ProcessInstanceDelegate.java
  runner/src/main/java/org/camunda/bpm/scenario/delegate/VariablesAwareDelegate.java
  runner/src/main/java/org/camunda/bpm/scenario/impl/MockedProcessRunnerImpl.java
  runner/src/main/java/org/camunda/bpm/scenario/impl/WaitstateExecutable.java
  runner/src/main/java/org/camunda/bpm/scenario/impl/delegate/EventSubscriptionDelegateImpl.java
  runner/src/main/java/org/camunda/bpm/scenario/impl/delegate/ProcessInstanceDelegateImpl.java
  test/test-7.0/src/test/java/org/camunda/bpm/scenario/test/variables/VariablesTest.java
  test/test-7.0/src/test/resources/org/camunda/bpm/scenario/test/variables/VariablesTest.bpmn
Labels: feature

#77 Create a scenario report module
  example/pom.xml
  pom.xml
  report/pom.xml
  report/src/main/java/org/camunda/bpm/scenario/report/Report.java
  report/src/main/java/org/camunda/bpm/scenario/report/bpmn/AbstractProcessReport.java
  report/src/main/java/org/camunda/bpm/scenario/report/bpmn/BpmnModelInstanceColoring.java
  report/src/main/java/org/camunda/bpm/scenario/report/bpmn/Case.java
  report/src/main/java/org/camunda/bpm/scenario/report/bpmn/ProcessCoverageReport.java
  report/src/main/java/org/camunda/bpm/scenario/report/bpmn/ProcessScenarioReport.java
  report/src/main/java/org/camunda/bpm/scenario/report/bpmn/ProcessScenarioTestReportGenerator.java
  report/src/main/java/org/camunda/bpm/scenario/report/junit/ProcessEngineExtensionWithReporting.java
  report/src/main/java/org/camunda/bpm/scenario/report/junit/ProcessEngineRuleWithReporting.java
  test/test-7.6/pom.xml
  test/test-7.6/src/test/java/DinnerTest.java
  test/test-7.6/src/test/java/org/camunda/bpm/scenario/test/report/dinner/DinnerTest.java
  test/test-7.6/src/test/java/org/camunda/bpm/scenario/test/report/insurance/InsuranceTest.java
  test/test-7.6/src/test/java/org/camunda/bpm/scenario/test/report/insurance/MapDmnResult.java
  test/test-7.6/src/test/resources/Dinner.bpmn
  test/test-7.6/src/test/resources/camunda-platform-scenario.properties
  test/test-7.6/src/test/resources/org/camunda/bpm/scenario/test/report/dinner/Dinner.bpmn
  test/test-7.6/src/test/resources/org/camunda/bpm/scenario/test/report/dinner/Dinner.dmn
  test/test-7.6/src/test/resources/org/camunda/bpm/scenario/test/report/insurance/DocumentRequest.bpmn
  test/test-7.6/src/test/resources/org/camunda/bpm/scenario/test/report/insurance/InsuranceApplication.bpmn
  test/test-7.6/src/test/resources/org/camunda/bpm/scenario/test/report/insurance/RiskCheck.dmn
Labels: feature

#82 Support reporting for process models with more than one executable process
  report/src/main/java/org/camunda/bpm/scenario/report/bpmn/AbstractProcessReport.java
  report/src/main/java/org/camunda/bpm/scenario/report/bpmn/BpmnModelInstanceColoring.java
  report/src/main/java/org/camunda/bpm/scenario/report/bpmn/Case.java
  report/src/main/java/org/camunda/bpm/scenario/report/bpmn/ProcessCoverageReport.java
  report/src/main/java/org/camunda/bpm/scenario/report/bpmn/ProcessScenarioReport.java
  report/src/main/java/org/camunda/bpm/scenario/report/bpmn/ProcessScenarioTestReportGenerator.java
  test/test-7.6/src/test/resources/camunda-platform-scenario.properties
Labels: improve

#84 Feature/simplify junit5 process engine extension
  pom.xml
  report/src/main/java/org/camunda/bpm/scenario/report/junit/ProcessEngineExtensionWithReporting.java
  test/pom.xml
  test/test-7.7/pom.xml
  test/test-7.7/src/main/resources/.keep
  test/test-7.7/src/test/java/org/camunda/bpm/scenario/test/report/dinner/DinnerTest.java
  test/test-7.7/src/test/resources/camunda.cfg.xml
  test/test-7.7/src/test/resources/logback-test.xml
  test/test-7.7/src/test/resources/org/camunda/bpm/scenario/test/report/dinner/Dinner.bpmn
  test/test-7.7/src/test/resources/org/camunda/bpm/scenario/test/report/dinner/Dinner.dmn
Labels: chore, improve

#85 Bugfix for report not generated for specific features
  cucumber/src/main/java/org/camunda/bpm/scenario/cucumber/CamundaCucumberPlugin.java
  report/src/main/java/org/camunda/bpm/scenario/report/cucumber/CamundaCucumberPluginReportGenerator.java
  test/test-7.6/src/test/java/org/camunda/bpm/scenario/test/cucumber/DinnerStepDefinitions.java
  test/test-7.6/src/test/java/org/camunda/bpm/scenario/test/cucumber/DinnerWithCucumberStepDefinitions.java
  test/test-7.6/src/test/java/org/camunda/bpm/scenario/test/cucumber/DinnerWithCucumberTest.java
  test/test-7.6/src/test/resources/org/camunda/bpm/scenario/test/cucumber/Dinner.feature
  test/test-7.6/src/test/resources/org/camunda/bpm/scenario/test/cucumber/DinnerWithCucumber.bpmn
  test/test-7.6/src/test/resources/org/camunda/bpm/scenario/test/cucumber/DinnerWithCucumber.feature
Labels: fix
